# Generated by Django 6.0.4 on 2026-05-01 19:40

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bewohner",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Externe, nicht sprechende Kennung fuer URLs und UI.",
                        unique=True,
                    ),
                ),
                (
                    "resident_number",
                    models.CharField(
                        help_text="Interne Bewohnernummer aus dem Fachsystem.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("room_label", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktiv"),
                            ("inactive", "Inaktiv"),
                            ("archived", "Archiviert"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bewohner",
                "verbose_name_plural": "Bewohner",
                "ordering": ["last_name", "first_name", "resident_number"],
            },
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Stabile Formularfamilie, z. B. antrag-kurzzeitpflege.",
                        max_length=80,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        help_text="Fortlaufende Versionsnummer innerhalb einer Formularfamilie.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("published", "Veroeffentlicht"),
                            ("retired", "Ausgemustert"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("is_archivable", models.BooleanField(default=True)),
                ("review_required", models.BooleanField(default=True)),
                (
                    "retention_period_days",
                    models.PositiveIntegerField(
                        default=3650,
                        help_text="Aufbewahrungsdauer fuer zugehoerige Archivunterlagen.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(36500),
                        ],
                    ),
                ),
                (
                    "schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Abgeleitete, cachebare Struktur fuer Render- und Validierungszwecke.",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replaced_by_versions",
                        to="form_builder.form",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Formular",
                "verbose_name_plural": "Formulare",
                "ordering": ["key", "-version"],
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.SlugField(max_length=80)),
                ("label", models.CharField(max_length=255)),
                ("help_text", models.TextField(blank=True)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("textarea", "Mehrzeilig"),
                            ("integer", "Ganzzahl"),
                            ("decimal", "Dezimalzahl"),
                            ("date", "Datum"),
                            ("datetime", "Datum und Uhrzeit"),
                            ("boolean", "Ja/Nein"),
                            ("select", "Auswahl"),
                            ("multiselect", "Mehrfachauswahl"),
                            ("radio", "Radiogruppe"),
                            ("email", "E-Mail"),
                            ("phone", "Telefon"),
                            ("file", "Datei"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="Technische Reihenfolge innerhalb des Formulars.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("sensitive", "Sensibel"),
                            ("special_category", "Besonders sensibel"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=24,
                    ),
                ),
                ("placeholder", models.CharField(blank=True, max_length=255)),
                ("default_value", models.JSONField(blank=True, null=True)),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Nur fuer Auswahlfelder; Liste aus stabilen value/label-Eintraegen.",
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Serverseitige Regeln wie min/max, Regex, Dateitypen oder Bereichswerte.",
                    ),
                ),
                (
                    "ui_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Darstellungsoptionen fuer Builder und spaetere PDF-Ausgabe.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fields",
                        to="form_builder.form",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formularfeld",
                "verbose_name_plural": "Formularfelder",
                "ordering": ["form", "position", "key"],
            },
        ),
        migrations.CreateModel(
            name="FormEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Externe, nicht sprechende Kennung fuer UI und Links.",
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("in_review", "In Pruefung"),
                            ("approved", "Freigegeben"),
                            ("rejected", "Zurueckgewiesen"),
                            ("ready_to_send", "Bereit zum Versand"),
                            ("archived", "Archiviert"),
                            ("deleted", "Geloescht"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                    ),
                ),
                (
                    "form_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Eingefrorene Formularstruktur fuer spaetere Nachvollziehbarkeit.",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Rohwerte nach Feld-Key, immer serverseitig validiert.",
                    ),
                ),
                (
                    "validation_errors",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Zuletzt bekannte serverseitige Fehler pro Feld.",
                    ),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bewohner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="form_entries",
                        to="form_builder.bewohner",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="form_builder.form",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_form_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Formulareintrag",
                "verbose_name_plural": "Formulareintraege",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Erstellt"),
                            ("updated", "Aktualisiert"),
                            ("deleted", "Geloescht"),
                            ("viewed", "Angesehen"),
                            ("validated", "Validiert"),
                            ("status_changed", "Status geaendert"),
                            ("pdf_rendered", "PDF erzeugt"),
                            ("sent", "Versandt"),
                            ("download", "Heruntergeladen"),
                            ("permission_denied", "Zugriff verweigert"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("target_model", models.CharField(max_length=100)),
                ("target_id", models.UUIDField()),
                ("remote_addr", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("message", models.CharField(blank=True, max_length=255)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Zusaetzliche, nicht frei formulierte Audit-Daten.",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bewohner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="form_builder.bewohner",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="form_builder.form",
                    ),
                ),
                (
                    "form_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="form_builder.formentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit-Log",
                "verbose_name_plural": "Audit-Logs",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="FormRecipient",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[("to", "An"), ("cc", "Cc"), ("bcc", "Bcc")],
                        default="to",
                        max_length=8,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("smtp", "SMTP"), ("microsoft_graph", "Microsoft Graph")],
                        db_index=True,
                        default="smtp",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=True,
                        help_text="Standardempfaenger fuer neue Versandvorgaenge dieses Formulars.",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Kanalbezogene Zusatzparameter, z. B. Graph-Mandant oder SMTP-Profilkennung.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipients",
                        to="form_builder.form",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Formularempfaenger",
                "verbose_name_plural": "Formularempfaenger",
                "ordering": ["form", "recipient_type", "email"],
            },
        ),
        migrations.CreateModel(
            name="FormSchedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manuell"),
                            ("immediate", "Sofort"),
                            ("scheduled", "Geplant"),
                        ],
                        db_index=True,
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktiv"),
                            ("paused", "Pausiert"),
                            ("retired", "Stillgelegt"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("timezone", models.CharField(default="Europe/Berlin", max_length=64)),
                ("cron_expression", models.CharField(blank=True, max_length=120)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Zusatzregeln fuer Trigger, Filter oder Versandfenster.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules",
                        to="form_builder.form",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Formularzeitplan",
                "verbose_name_plural": "Formularzeitplaene",
                "ordering": ["form", "name"],
            },
        ),
        migrations.CreateModel(
            name="PDFDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "document_kind",
                    models.CharField(
                        choices=[
                            ("review", "Review-PDF"),
                            ("final", "Finales PDF"),
                            ("archive", "Archiv-PDF"),
                        ],
                        db_index=True,
                        default="review",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("generated", "Erzeugt"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "storage_key",
                    models.CharField(
                        help_text="Interner geschuetzter Speicherpfad oder Objekt-Key, niemals als oeffentlicher Link ausliefern.",
                        max_length=512,
                        unique=True,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(default="application/pdf", max_length=100)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
                (
                    "access_policy",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Vorbereitung fuer serverseitige Berechtigungspruefung und Download-Auditierung.",
                    ),
                ),
                (
                    "bewohner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pdf_documents",
                        to="form_builder.bewohner",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pdf_documents",
                        to="form_builder.form",
                    ),
                ),
                (
                    "form_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pdf_documents",
                        to="form_builder.formentry",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF-Dokument",
                "verbose_name_plural": "PDF-Dokumente",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OutboxItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("sent", "Versendet"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("smtp", "SMTP"), ("microsoft_graph", "Microsoft Graph")],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Strukturierte Versanddaten fuer Worker, niemals als unkontrollierter Freitextspeicher.",
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=100)),
                ("last_error_message", models.TextField(blank=True)),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                (
                    "provider_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Reduzierte Provider-Rueckgaben fuer Retry, Monitoring und spaetere Audit-Events.",
                    ),
                ),
                (
                    "bewohner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_items",
                        to="form_builder.bewohner",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_items",
                        to="form_builder.form",
                    ),
                ),
                (
                    "form_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_items",
                        to="form_builder.formentry",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_items",
                        to="form_builder.formrecipient",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbox_items",
                        to="form_builder.formschedule",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pdf_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbox_items",
                        to="form_builder.pdfdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ausgangskorb-Eintrag",
                "verbose_name_plural": "Ausgangskorb-Eintraege",
                "ordering": ["next_attempt_at", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SentFormArchive",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "recipient_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Eingefrorene Empfaenger- und Kanalinformationen fuer Nachvollziehbarkeit.",
                    ),
                ),
                (
                    "delivery_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Eingefrorene Versand- und Providerdaten fuer revisionssichere Archivierung.",
                    ),
                ),
                ("sent_at", models.DateTimeField(db_index=True)),
                (
                    "archived_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("retention_until", models.DateTimeField(blank=True, null=True)),
                (
                    "archive_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Vorbereitung fuer Berechtigungspruefung, Download-Audit und spaetere Aufbewahrungsjobs.",
                    ),
                ),
                (
                    "archived_pdf",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional separates Archiv-PDF, falls vom Versand-PDF abweichend.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_sent_records",
                        to="form_builder.pdfdocument",
                    ),
                ),
                (
                    "bewohner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_archives",
                        to="form_builder.bewohner",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_archives",
                        to="form_builder.form",
                    ),
                ),
                (
                    "form_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_archives",
                        to="form_builder.formentry",
                    ),
                ),
                (
                    "outbox_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archive_records",
                        to="form_builder.outboxitem",
                    ),
                ),
                (
                    "pdf_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archive_records",
                        to="form_builder.pdfdocument",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Versandarchiv",
                "verbose_name_plural": "Versandarchiv",
                "ordering": ["-archived_at"],
            },
        ),
        migrations.AddIndex(
            model_name="bewohner",
            index=models.Index(fields=["public_id"], name="form_builde_public__0323cc_idx"),
        ),
        migrations.AddIndex(
            model_name="bewohner",
            index=models.Index(
                fields=["resident_number", "status"], name="form_builde_residen_28532d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bewohner",
            index=models.Index(
                fields=["last_name", "first_name"], name="form_builde_last_na_5d18a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="form",
            index=models.Index(fields=["key", "status"], name="form_builde_key_c0b070_idx"),
        ),
        migrations.AddIndex(
            model_name="form",
            index=models.Index(
                fields=["status", "published_at"], name="form_builde_status_9112f4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="form",
            constraint=models.UniqueConstraint(
                fields=("key", "version"), name="uniq_form_key_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="form",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "published")),
                fields=("key",),
                name="uniq_published_form_per_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="form",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("published_at__isnull", False), ("status", "published")),
                    models.Q(("status", "published"), _negated=True),
                    _connector="OR",
                ),
                name="form_published_requires_timestamp",
            ),
        ),
        migrations.AddIndex(
            model_name="field",
            index=models.Index(fields=["form", "is_active"], name="form_builde_form_id_3e48a8_idx"),
        ),
        migrations.AddIndex(
            model_name="field",
            index=models.Index(
                fields=["field_type", "sensitivity"], name="form_builde_field_t_79f55f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="field",
            constraint=models.UniqueConstraint(
                fields=("form", "key"), name="uniq_field_key_per_form"
            ),
        ),
        migrations.AddConstraint(
            model_name="field",
            constraint=models.UniqueConstraint(
                fields=("form", "position"), name="uniq_field_position_per_form"
            ),
        ),
        migrations.AddIndex(
            model_name="formentry",
            index=models.Index(fields=["public_id"], name="form_builde_public__28d3d2_idx"),
        ),
        migrations.AddIndex(
            model_name="formentry",
            index=models.Index(
                fields=["status", "updated_at"], name="form_builde_status_491548_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formentry",
            index=models.Index(
                fields=["bewohner", "status"], name="form_builde_bewohne_220c3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formentry",
            index=models.Index(fields=["form", "status"], name="form_builde_form_id_20a18b_idx"),
        ),
        migrations.AddConstraint(
            model_name="formentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("locked_at__isnull", True), ("locked_by__isnull", True)),
                    models.Q(("locked_at__isnull", False), ("locked_by__isnull", False)),
                    _connector="OR",
                ),
                name="form_entry_lock_fields_match",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["target_model", "target_id"], name="form_builde_target__b22a23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["event_type", "occurred_at"], name="form_builde_event_t_84de55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["bewohner", "occurred_at"], name="form_builde_bewohne_b04f15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["form_entry", "occurred_at"], name="form_builde_form_en_f4cde3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formrecipient",
            index=models.Index(fields=["form", "is_active"], name="form_builde_form_id_f2122b_idx"),
        ),
        migrations.AddIndex(
            model_name="formrecipient",
            index=models.Index(
                fields=["channel", "is_active"], name="form_builde_channel_fc8873_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="formrecipient",
            constraint=models.UniqueConstraint(
                fields=("form", "email", "recipient_type", "channel"),
                name="uniq_form_recipient_per_channel",
            ),
        ),
        migrations.AddConstraint(
            model_name="formrecipient",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("form",),
                name="uniq_default_recipient_per_form",
            ),
        ),
        migrations.AddIndex(
            model_name="formschedule",
            index=models.Index(fields=["form", "status"], name="form_builde_form_id_e3d752_idx"),
        ),
        migrations.AddIndex(
            model_name="formschedule",
            index=models.Index(
                fields=["next_run_at", "status"], name="form_builde_next_ru_bd4d58_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="formschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_at__isnull", True), ("start_at__lte", models.F("end_at")), _connector="OR"
                ),
                name="form_schedule_valid_window",
            ),
        ),
        migrations.AddIndex(
            model_name="pdfdocument",
            index=models.Index(
                fields=["form_entry", "document_kind"], name="form_builde_form_en_74f4d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pdfdocument",
            index=models.Index(
                fields=["bewohner", "status"], name="form_builde_bewohne_a0487d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outboxitem",
            index=models.Index(
                fields=["status", "next_attempt_at"], name="form_builde_status_6f9a02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outboxitem",
            index=models.Index(fields=["channel", "status"], name="form_builde_channel_215a6f_idx"),
        ),
        migrations.AddIndex(
            model_name="outboxitem",
            index=models.Index(
                fields=["form_entry", "status"], name="form_builde_form_en_6d36e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outboxitem",
            index=models.Index(
                fields=["bewohner", "status"], name="form_builde_bewohne_e64807_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="outboxitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_attempts__gte", 1)), name="outbox_item_max_attempts_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="outboxitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_count__gte", 0)),
                name="outbox_item_attempt_count_gte_0",
            ),
        ),
        migrations.AddIndex(
            model_name="sentformarchive",
            index=models.Index(
                fields=["bewohner", "archived_at"], name="form_builde_bewohne_7f4bb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sentformarchive",
            index=models.Index(
                fields=["form_entry", "archived_at"], name="form_builde_form_en_634ae6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sentformarchive",
            index=models.Index(fields=["retention_until"], name="form_builde_retenti_de09b2_idx"),
        ),
    ]
