# Generated by Django 5.2.13 on 2026-05-02 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_builder", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formrecipient",
            options={
                "ordering": ["form", "recipient_type", "email"],
                "verbose_name": "Formular-E-Mail-Ziel",
                "verbose_name_plural": "Formular-E-Mail-Ziele",
            },
        ),
        migrations.RemoveConstraint(
            model_name="formrecipient",
            name="uniq_default_recipient_per_form",
        ),
        migrations.AddField(
            model_name="formrecipient",
            name="body_template",
            field=models.TextField(
                blank=True, help_text="Optionaler E-Mail-Text. Platzhalter wie im Betreff nutzbar."
            ),
        ),
        migrations.AddField(
            model_name="formrecipient",
            name="dispatch_frequency",
            field=models.CharField(
                blank=True,
                choices=[("manual", "Manuell"), ("daily", "Taeglich"), ("weekly", "Woechentlich")],
                help_text="Standard-Rhythmus fuer Versandplanung.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="formrecipient",
            name="dispatch_time",
            field=models.TimeField(
                blank=True,
                help_text="Regulaere Versandzeit fuer dieses Formular und diesen Empfaenger.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="formrecipient",
            name="dispatch_weekday",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="0=Montag bis 6=Sonntag, nur fuer woechentliche Planung.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
        migrations.AddField(
            model_name="formrecipient",
            name="subject_template",
            field=models.CharField(
                blank=True,
                help_text="Optionaler Betreff. Platzhalter: {form}, {name}, {vorname}, {pkz}, {aktenzeichen}.",
                max_length=255,
            ),
        ),
    ]
