# Generated by Django 5.2.13 on 2026-05-02 20:36

from django.db import migrations, models


def copy_recipient_ids_from_config(apps, schema_editor):
    FormSchedule = apps.get_model("form_builder", "FormSchedule")
    for schedule in FormSchedule.objects.all():
        config = schedule.config or {}
        recipient_ids = config.get("recipient_ids") or []
        if recipient_ids:
            schedule.recipients.add(*recipient_ids)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("form_builder", "0002_alter_formrecipient_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formschedule",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                help_text="E-Mail-Ziele, die mit diesem Zeitplan verbunden sind.",
                related_name="schedules",
                to="form_builder.formrecipient",
            ),
        ),
        migrations.RunPython(copy_recipient_ids_from_config, noop_reverse),
    ]
