# Generated by ChatGPT for professional employee access controls.
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("form_builder", "0003_formschedule_recipients"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccessProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "can_dashboard",
                    models.BooleanField(default=True, verbose_name="Dashboard sehen"),
                ),
                ("can_forms", models.BooleanField(default=True, verbose_name="Formulare sehen")),
                (
                    "can_create",
                    models.BooleanField(default=True, verbose_name="Vorgaenge erstellen"),
                ),
                ("can_send", models.BooleanField(default=True, verbose_name="Schicken / Versand")),
                ("can_archive", models.BooleanField(default=True, verbose_name="Archiv sehen")),
                (
                    "can_settings",
                    models.BooleanField(default=False, verbose_name="Einstellungen sehen"),
                ),
                (
                    "can_manage_settings",
                    models.BooleanField(default=False, verbose_name="Einstellungen verwalten"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_builder_useraccessprofile_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_builder_useraccessprofile_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_access_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitarbeiter-Zugriff",
                "verbose_name_plural": "Mitarbeiter-Zugriffe",
            },
        ),
    ]
