# Generated by Django 5.2.13 on 2026-05-04 08:18

import hashlib
import json

from django.db import migrations, models


def _calculate_hash(log, previous_hash: str) -> str:
    payload = {
        "id": str(log.id),
        "occurred_at": log.occurred_at.isoformat() if log.occurred_at else "",
        "actor_id": str(log.actor_id or ""),
        "event_type": log.event_type,
        "target_model": log.target_model,
        "target_id": str(log.target_id),
        "bewohner_id": str(log.bewohner_id or ""),
        "form_id": str(log.form_id or ""),
        "form_entry_id": str(log.form_entry_id or ""),
        "remote_addr": log.remote_addr or "",
        "user_agent": log.user_agent or "",
        "message": log.message or "",
        "metadata": log.metadata or {},
        "previous_hash": previous_hash or "",
    }
    encoded = json.dumps(payload, sort_keys=True, default=str, separators=(",", ":")).encode(
        "utf-8"
    )
    return hashlib.sha256(encoded).hexdigest()


def backfill_audit_hash_chain(apps, schema_editor):
    AuditLog = apps.get_model("form_builder", "AuditLog")
    previous_hash = ""
    for log in AuditLog.objects.order_by("occurred_at", "id"):
        entry_hash = _calculate_hash(log, previous_hash)
        AuditLog.objects.filter(pk=log.pk).update(
            previous_hash=previous_hash, entry_hash=entry_hash
        )
        previous_hash = entry_hash


class Migration(migrations.Migration):
    dependencies = [
        ("form_builder", "0005_alter_useraccessprofile_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="entry_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="SHA-256 Hash dieses Audit-Eintrags inklusive previous_hash.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="previous_hash",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="SHA-256 Hash des vorherigen Audit-Eintrags fuer eine pruefbare Hash-Kette.",
                max_length=64,
            ),
        ),
        migrations.RunPython(backfill_audit_hash_chain, migrations.RunPython.noop),
    ]
