# Generated by Django 5.2.13 on 2026-05-04 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_builder", "0006_audit_hash_chain"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bewohner",
            name="org_unit",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stabiler Standort-/Abteilungscode fuer rollenbasierte Zugriffsbeschraenkung.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="org_unit",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Optionaler Standort-/Abteilungscode fuer scoped Rollen.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="useraccessprofile",
            name="allowed_form_keys",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Optionale Liste von Formular-Keys. Leer bedeutet: alle Formularfamilien im Datenbereich.",
                verbose_name="Erlaubte Formularfamilien",
            ),
        ),
        migrations.AddField(
            model_name="useraccessprofile",
            name="org_units",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste stabiler Codes, z. B. Standort/Abteilung. Leer bedeutet: kein Organisationsbereich.",
                verbose_name="Organisationseinheiten",
            ),
        ),
        migrations.AddField(
            model_name="useraccessprofile",
            name="scope_mode",
            field=models.CharField(
                choices=[
                    ("all", "Alle zulaessigen Daten"),
                    ("org_units", "Nur Organisationseinheiten"),
                    ("own", "Nur eigene Vorgaenge"),
                ],
                db_index=True,
                default="own",
                help_text="Begrenzt Formulare, Bewohner, PDFs, Ausgangskorb und Archiv auf einen organisatorischen Bereich.",
                max_length=16,
                verbose_name="Datenbereich",
            ),
        ),
        migrations.AddIndex(
            model_name="bewohner",
            index=models.Index(
                fields=["org_unit", "status"], name="form_builde_org_uni_de6cd0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="form",
            index=models.Index(
                fields=["org_unit", "status"], name="form_builde_org_uni_4d7975_idx"
            ),
        ),
    ]
