# Generated by ChatGPT for Prompt 6 PDF template placement.

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import form_builder.pdf_template_models


class Migration(migrations.Migration):
    dependencies = [
        ("form_builder", "0013_excel_imports"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to=form_builder.pdf_template_models.pdf_template_upload_to,
                    ),
                ),
                ("content_type", models.CharField(default="application/pdf", max_length=100)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("page_count", models.PositiveIntegerField(default=0)),
                ("page_metadata", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("active", "Aktiv"),
                            ("retired", "Ausgemustert"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_builder_pdftemplate_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pdf_templates",
                        to="form_builder.form",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_builder_pdftemplate_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF-Vorlage",
                "verbose_name_plural": "PDF-Vorlagen",
                "ordering": ["form", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PDFTemplatePlacement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "page_number",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "x",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "y",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "width",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.001),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.001),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("checkbox", "Checkbox"),
                            ("date", "Datum"),
                            ("signature", "Unterschrift"),
                        ],
                        default="text",
                        max_length=24,
                    ),
                ),
                (
                    "font_size",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(6),
                            django.core.validators.MaxValueValidator(28),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_builder_pdftemplateplacement_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_template_placements",
                        to="form_builder.field",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="form_builder.pdftemplate",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_builder_pdftemplateplacement_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF-Feldplatzierung",
                "verbose_name_plural": "PDF-Feldplatzierungen",
                "ordering": ["template", "page_number", "field__position", "field__key"],
            },
        ),
        migrations.AddIndex(
            model_name="pdftemplate",
            index=models.Index(
                fields=["form", "status", "is_active"], name="form_builde_form_id_3ad4b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pdftemplate",
            index=models.Index(fields=["sha256"], name="form_builde_sha256_d8b3f6_idx"),
        ),
        migrations.AddIndex(
            model_name="pdftemplateplacement",
            index=models.Index(
                fields=["template", "page_number", "is_active"],
                name="form_builde_templat_c98df8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pdftemplateplacement",
            index=models.Index(
                fields=["field", "is_active"], name="form_builde_field_i_d2b7fa_idx"
            ),
        ),
    ]
