# Generated by ChatGPT for Prompt 8 ActionItem/reminder foundation

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_builder", "0015_docx_templates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_field_key", models.SlugField(blank=True, db_index=True, max_length=120)),
                ("source_group_key", models.SlugField(blank=True, db_index=True, max_length=120)),
                ("source_row_key", models.CharField(blank=True, db_index=True, max_length=120)),
                ("source_rule_key", models.CharField(blank=True, db_index=True, max_length=160)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "assigned_to_label",
                    models.CharField(
                        blank=True,
                        help_text="Freitext-Verantwortlicher aus importierten Tabellen, falls kein Benutzer zugeordnet ist.",
                        max_length=255,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Niedrig"),
                            ("normal", "Normal"),
                            ("high", "Hoch"),
                            ("critical", "Kritisch"),
                        ],
                        default="normal",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Offen"),
                            ("in_progress", "In Bearbeitung"),
                            ("done", "Erledigt"),
                            ("verified", "Verifiziert"),
                            ("cancelled", "Abgebrochen"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=24,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_action_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_builder_actionitem_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_items",
                        to="form_builder.formentry",
                    ),
                ),
                (
                    "source_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_items",
                        to="form_builder.field",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_builder_actionitem_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_action_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Massnahme",
                "verbose_name_plural": "Massnahmen",
                "ordering": ["status", "due_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActionItemRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("source_field_key", models.SlugField(blank=True, max_length=120)),
                ("source_group_key", models.SlugField(blank=True, max_length=120)),
                ("source_column_key", models.SlugField(blank=True, max_length=120)),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("equals", "ist gleich"),
                            ("not_equals", "ist nicht gleich"),
                            ("contains", "enthaelt"),
                            ("is_empty", "ist leer"),
                            ("is_not_empty", "ist nicht leer"),
                            ("boolean_true", "ist ja/aktiv"),
                            ("boolean_false", "ist nein/inaktiv"),
                        ],
                        default="equals",
                        max_length=24,
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=255)),
                (
                    "title_template",
                    models.CharField(default="Massnahme aus {form}", max_length=255),
                ),
                ("description_template", models.TextField(blank=True)),
                ("assigned_to_field_key", models.SlugField(blank=True, max_length=120)),
                ("due_at_field_key", models.SlugField(blank=True, max_length=120)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Niedrig"),
                            ("normal", "Normal"),
                            ("high", "Hoch"),
                            ("critical", "Kritisch"),
                        ],
                        default="normal",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_item_rules_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_builder_actionitemrule_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_item_rules",
                        to="form_builder.form",
                    ),
                ),
                (
                    "source_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_item_rules",
                        to="form_builder.field",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_builder_actionitemrule_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Massnahmen-Regel",
                "verbose_name_plural": "Massnahmen-Regeln",
                "ordering": ["form", "name"],
            },
        ),
        migrations.CreateModel(
            name="ActionItemReminderLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("due_soon", "Bald faellig"),
                            ("overdue", "Ueberfaellig"),
                            ("escalation", "Eskalation"),
                            ("review_overdue", "Review ueberfaellig"),
                        ],
                        max_length=32,
                    ),
                ),
                ("dedupe_key", models.CharField(max_length=255, unique=True)),
                ("sent_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "action_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_logs",
                        to="form_builder.actionitem",
                    ),
                ),
                (
                    "form_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_logs",
                        to="form_builder.formentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Massnahmen-Erinnerung",
                "verbose_name_plural": "Massnahmen-Erinnerungen",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="actionitem",
            constraint=models.UniqueConstraint(
                fields=("source_entry", "source_rule_key", "source_row_key", "source_field_key"),
                name="uniq_action_item_source_dedupe",
            ),
        ),
        migrations.AddIndex(
            model_name="actionitem",
            index=models.Index(fields=["status", "due_at"], name="form_builde_status_2c9ab9_idx"),
        ),
        migrations.AddIndex(
            model_name="actionitem",
            index=models.Index(
                fields=["assigned_to", "status"], name="form_builde_assigne_d5d6df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actionitem",
            index=models.Index(
                fields=["source_entry", "status"], name="form_builde_source__b1d915_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actionitem",
            index=models.Index(
                fields=["source_group_key", "source_row_key"], name="form_builde_source__42dc10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actionitemrule",
            index=models.Index(fields=["form", "is_active"], name="form_builde_form_id_0b17d9_idx"),
        ),
        migrations.AddIndex(
            model_name="actionitemrule",
            index=models.Index(
                fields=["source_group_key", "source_column_key"],
                name="form_builde_source__629d80_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="actionitemreminderlog",
            index=models.Index(fields=["kind", "sent_at"], name="form_builde_kind_01f69b_idx"),
        ),
        migrations.AddIndex(
            model_name="actionitemreminderlog",
            index=models.Index(
                fields=["action_item", "kind"], name="form_builde_action__18b8ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actionitemreminderlog",
            index=models.Index(
                fields=["form_entry", "kind"], name="form_builde_form_en_d29ecf_idx"
            ),
        ),
    ]
