# Generated by ChatGPT for QR context support.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import form_builder.qr_context_models


class Migration(migrations.Migration):
    dependencies = [
        ("form_builder", "0016_action_items"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QRFormContext",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=255)),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        default=form_builder.qr_context_models.generate_qr_token,
                        max_length=80,
                        unique=True,
                    ),
                ),
                (
                    "context_type",
                    models.CharField(blank=True, help_text="Optionaler Kontexttyp, z. B. room, location, asset oder resident.", max_length=40),
                ),
                (
                    "context_key",
                    models.SlugField(blank=True, help_text="Stabiler nicht sensibler Kontextschluessel, z. B. kueche-1 oder raum-a-12.", max_length=120),
                ),
                (
                    "context_payload",
                    models.JSONField(blank=True, default=dict, help_text="Nicht sensible Vorbelegungen fuer Formularfelder."),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                (
                    "bewohner",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="qr_contexts", to="form_builder.bewohner"),
                ),
                (
                    "created_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="form_builder_qrformcontext_created", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "form",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="qr_contexts", to="form_builder.form"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="form_builder_qrformcontext_updated", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "QR-Formularkontext",
                "verbose_name_plural": "QR-Formularkontexte",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="qrformcontext",
            index=models.Index(fields=["form", "is_active"], name="form_builde_form_id_e60cd1_idx"),
        ),
        migrations.AddIndex(
            model_name="qrformcontext",
            index=models.Index(fields=["expires_at", "is_active"], name="form_builde_expires_d2a9b9_idx"),
        ),
        migrations.AddIndex(
            model_name="qrformcontext",
            index=models.Index(fields=["context_type", "context_key"], name="form_builde_context_16f81f_idx"),
        ),
    ]
